name: Update
on: workflow_dispatch

jobs:
  update:
    runs-on: [ 'self-hosted', 'mc-versions' ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set repository as a safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update mc-versions
        run: make update

      - name: Commit and Push update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(./commitmsg.ts)" && git push || echo 'No changes'