name: Update
on: workflow_dispatch

jobs:
  update:
    runs-on: [ 'self-hosted', 'mc-versions' ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOTRISING_TOKEN }}
          fetch-depth: 0

      - name: Update mc-versions
        run: make update

      - name: Commit and Push update
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit --no-gpg-sign -m "$(./commitmsg.ts)" && git push || echo 'No changes'